name: 'clickhouse_epicor'
version: '1.0.0'

profile: 'clickhouse_epicor'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  clickhouse_epicor:
    raw:
      +materialized: table
    bronze:
      +materialized: table
